### ISSUE TITLE
Add Rails Admin path helpers in application

### ISSUE THREAD

**Issue by brutuscat** [railsadminteam/rails_admin#1027]
It would be great to be able to link from the app to the rails admin page. Something like this:

```
#@something.id = 4
app.rails_admin_edit_something_path(@something) -> /admin/something/4/edit
```

**Comment by MarkOates** [comment]
Route helpers can be accessed directly from `RailsAdmin.railtie_routes_url_helpers`.

In the link provided above (https://github.com/sferik/rails_admin/wiki/Using-RailsAdmin-routes), you could create, for example, an `edit_path` URL like this:

```ruby
RailsAdmin.railtie_routes_url_helpers.edit_path(model_name: 'author', id: Author.first.id)
```

Note that because this is outside the context of a request, there is no host.  So if you needed to use the `*_url` helper methods, you would also include a `host:` param as well as shown here:

```ruby
RailsAdmin.railtie_routes_url_helpers.edit_url(model_name: 'author', id: Author.first.id, host: 'https://www.foo.com')
```

The other helpers `index_path`, `show_path`, etc. should all work the same, etc.
