### ISSUE TITLE
cancan, hash conditions on edit and new

### ISSUE THREAD

**Issue by aguilarsoto** [railsadminteam/rails_admin#1067]
Hello,

So Im using rails admin with cancan authentication, basically I had a rule on the ability that looked like this

can :manage, User, :id => user.id

everytime I edited a object on rails_admin the changes applied to the current user instead, after debugging I found the problem to be on rails_admin/config/actions/edit.rm specifically on the 

``` ruby
@authorization_adapter && @authorization_adapter.attributes_for(:update, @abstract_model).each do |name, value|
      @object.send("#{name}=", value)
end
```

since the attributes for returns id => ID_OF_CURRENT_USER this overrrides the id of the object and cause the update to affect the current_user instead of the user Im editing

Regards,
Marco Aguilar

**Comment by bartonmcguire** [comment]
This is still a bug, and while the suggested work around does prevent the issue, it's still a work around. And the original expression of this permission: `can :manage, User, :id => user.id` is CanCan's only formally documented method of assigning this permission. This *should* work.

It's unclear to me why [this block causing the issue](https://github.com/sferik/rails_admin/blob/9abc1be0c1fee006a7a746583461891911fe9330/lib/rails_admin/config/actions/edit.rb#L28) even exists. It seems the solution would be to simply remove it.

There's been a chain of issues opened since describing this bug.
