### ISSUE TITLE
Table names don't always get properly quoted

### ISSUE THREAD

**Issue by jasonswett** [railsadminteam/rails_admin#1631]
In lib/rails_admin/config/actions/dashboard.rb, on line 30, it produces an SQL query that doesn't quote the table name referenced (SELECT  "user".\* FROM "user"  ORDER BY user.updated_at desc). This is a problem if you have a table name like "user", which is a reserved word in PostgreSQL.

Here's a gist with a stack trace: https://gist.github.com/jasonswett/1da12e239266f20b17c2

I wrote a fix for this, but this would be my first open source contribution ever, so I might need a little hand-holding to get it in. I understand I'm supposed to write a failing spec, but I don't see a spec for dashboard.rb in what I would assume to be the logical place, spec/rails_admin/config/actions. If someone could help me find that, that would be appreciated.

**Comment by ohararyan** [comment]
Looks like this issue still exists as I've got the same problem currently. Is there any update on this?

**Comment by rnestler** [comment]
I also just hit that issue.

**Comment by rnestler** [comment]
I found the root cause: If not quoted postgres will downcase everything, so if I have a column name "FOO_BAR" and try to query it like `SELECT "foo".* FROM "fo" ORDER BY foo.FOO_BAR desc` it will be converted to `SELECT "foo".* FROM "fo" ORDER BY foo.foo_bar desc` which then won't work.

See https://stackoverflow.com/a/2878408/3497181
> Postgresql treats identifiers case insensitively when not quoted (**it actually folds them to lowercase internally**), and case sensitively when quoted; many people are not aware of this idiosyncrasy.

Rails / ActiveModel itself does the correct thing, so if I execute `Foo.order(:FOO_BAR)` it generates the correctly quoted SQL.
