### ISSUE TITLE
hbtm with order brokes edit page

### ISSUE THREAD

**Issue by yahor** [railsadminteam/rails_admin#2067]
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users, -> { order last_name: :asc }
end

group edit page:
ArgumentError - wrong number of arguments (1 for 0):
  rails_admin (0.6.3) lib/rails_admin/adapters/active_record/association.rb:61:in `read_only?'

**Comment by kaishin** [comment]
Having the same issue as well.

**Comment by yahor** [comment]
has_and_belongs_to_many :users, Proc.new { order last_name: :asc }
it works for me, thanks @kenjione

**Comment by CapnMorgan71** [comment]
Any updates on this? that did Proc new did not work for me.

**Comment by yushine** [comment]
It works for me, thanks @kenjione .
And do you know what's the reason?

**Comment by LucasAU** [comment]
FWIW I just hit this in 0.8.1, changing the '->' to 'proc' enabled the rails_admin edit page to load. There seems to be no other side-effects, but it's a bit annoying because the official docs all point to lambdas as the way to add a scope to the relation.

Is there an alternative to instance_eval that does not pass the receiver as an argument?

PS: I also tried adding a param to the lambda which did enable the edit page to function, but I started getting this deprecation warning around my site (I sometimes preload the association):

> DEPRECATION WARNING: The association scope 'tags' is instance dependent (the scope block takes an argument). Preloading happens before the individual instances are created. This means that there is no instance being passed to the association scope. This will most likely result in broken or incorrect behavior. Joining, Preloading and eager loading of these associations is deprecated and will be removed in the future.
