### ISSUE TITLE
The save object button acts as save and edit (only in production)

### ISSUE THREAD

**Issue by grillermo** [railsadminteam/rails_admin#2094]
Hi, i have some permissions that enable a certain user to edit an object only if its in certain state, once the user has changed the state it loses the edit permission, thanks to cancancan.
The problem is in production the save button is always defaulting to return to the edit view, and this breaks because the user has just lost permission and sees an ugly error.
In development and testing(with capybara) this does not happen, the save button redirects to the index as it should.
I noticed a hidden input with return_to, that has the wrong value.
The db is the same on dev and production, and this return_to value is wrong only in production.
Any ideas what could be causing it?

**Comment by dngrhm** [comment]
Sorry to bring back this thread, but I came across this thread in my search for answer for a similar question.  A real answer to this would have been super helpful.  I was having a similar problem with rails_admin_clone.  Saving the cloned model would result in returning to the unsaved clone.  This was caused by a double call situation due to pjax.  Disabling pjax fixed the issue for me https://github.com/sferik/rails_admin/wiki/Custom-action#double-pjax Saving returns to the page from which you originated the action.
