### ISSUE TITLE
fields.nested_form[:update_only] should always be false by default.

### ISSUE THREAD

**Issue by antoine-lizee** [railsadminteam/rails_admin#2626]
See the "first bug" in [this stack overflow answer](http://stackoverflow.com/a/36929302/1877609). 

It's a personal opinion, but I think that interpreting `accept_nested_attributes_for: ..., update_only:true` as "disable the form when creating the object" is a potential misunderstanding of the option, (for Rails 4), and should at least be documented in the wiki?

**Comment by ericcf** [comment]
@antoine-lizee as a first step, I've created a gist to reproduce the issue here: https://gist.github.com/ericcf/f4da02ca5bb80d889131f603448ee10c

There is a difference between `update_only: true` and `update_only: false`, which seems like a bug to me as well based on the description [in the Rails documentation](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#method-i-accepts_nested_attributes_for). In my example, `accepts_nested_attributes_for :dog, update_only: false` leads to being able to add a `Dog` record upon creation of a `Person`, which seems to be correct.

@sferik is this interpretation correct? Would you like a failing spec for this case or is more discussion necessary? Thanks.

**Comment by GProst** [comment]
We're having the same issues because of the misunderstanding of this option by Rails Admin. It's unexpected that you can't create a new association for a model when `update_only` is set to `true` for `accept_nested_attributes_for`

**Comment by myers** [comment]
BTW, if you do the following:

```
RailsAdmin.config do |config|
  config.model 'User' do
    base do
      configure :location do
        nested_form[:update_only] = false
      end
    end
  end
end
```

In order to get Rails Admin to show the child form when creating a instance, you will actually change the settings on the model as `nested_form` returns the same hash used to configure the model.

You should do this instead:

```
      configure :location do
        nested_form(nested_form.clone)
        nested_form[:update_only] = false
      end
```
