### ISSUE TITLE
Map Field

### ISSUE THREAD

**Issue by RocKhalil** [railsadminteam/rails_admin#3443]
I've been using this map field ( https://github.com/RocKhalil/rails_admin_map_field ) for some time, and I think it's a good option to include it in the main rails admin repo.

Do you think it's worth working on migrating it to the main repo or keep using it as an external gem ?

**Comment by codealchemy** [comment]
I have a some concerns around maintaining non-Rails-native functionality in `rails_admin` (which has been done for PaperTrail, Pundit, Carrierwave, etc.), mainly since it increases the maintenance burden of keeping up with any / all changes to those libraries in one place with one release process. It feels helpful (and easier now that we have the `railsadminteam` Github org) to have `rails_admin` keep / maintain an interface for these types of extensions, and split those out to separate gems (something I've been meaning to propose that over in the [Roadmap discussion](https://github.com/railsadminteam/rails_admin/discussions/3429)) - which would mean keeping that project as a separate gem, thoughts?

**Comment by RocKhalil** [comment]
Yes, makes total sense. Just like react-native-community, we can start porting useful packages into `railsadminteam` that can enhance `rails_admin` and its functionalities.
