### ISSUE TITLE
Custom theme overrides not working on `beta` releases

### ISSUE THREAD

**Issue by codealchemy** [railsadminteam/rails_admin#3466]
**Describe the bug**

When updating an existing app (using Rails 6 / Sprockets / asset pipeline), to `3.0.0.beta2` - custom theme overrides (following [theming docs](https://github.com/railsadminteam/rails_admin/wiki/Theming-and-customization#for-custom-theming-application-scoped-simply-override-these-files-in-your-app), which worked on `2.x.x` releases) are not being picked up. 

Specifically, anything defined in a projects `app/assets/stylesheets/rails_admin/custom/theming.scss` does not take precedence over RailsAdmin defaults (seems to be a load order issue for [imports](https://github.com/railsadminteam/rails_admin/blob/687867035b3a917623a3ccb01e07af0e532f47fa/app/assets/stylesheets/rails_admin.scss#L31)) .

Unsure if this applies to apps _not_ using `sprockets`.

This can be reproduced on the `dummy_app` for the current `master` (see below)

**Reproduction steps**

Repro using the `dummy_app` in RailsAdmin -> https://github.com/codealchemy/rails_admin/commit/1c8886f6a7328a034075c4855756c1aa271d5f8b

**Expected behavior**

Existing theme overrides will continue to work (between 2.x.x and 3.x.x releases using the asset pipeline) as described in the Wiki.

**Additional context**

`sassc-rails` - 2.1.2
`sassc` - 2.4.0
`sprockets` - 4.0.2
`rails` - 6.1.3.1 (also seen on 6.0 project)
`rails_admin` - 3.x beta releases

**Comment by mshibuya** [comment]
This was caused because when sassc tries to resolve imports, files available by relative path take precedence over files in asset_paths.
In #3414 RailsAdmin CSS was moved to `app/assets/stylesheet/rails_admin.scss`, so `@import "rails_admin/custom/theming";` picked `app/assets/stylesheet/rails_admin/custom/theming.scss`, which was directly accessible by the relative path.

Moving the CSS to `app/assets/stylesheet/rails_admin/application.scss` solved the issue.

**Comment by codealchemy** [comment]
Thanks!
