### ISSUE TITLE
FontAwesome - Only "solid" variant works on icons

### ISSUE THREAD

**Issue by newfylox** [railsadminteam/rails_admin#3594]
**Describe the bug**
When using rails_admin 2.x.x, I was able to use variants of icon with FontAwesome but not anymore after upgrading to rails_admin 3.x.x.

I'm using sprockets so using rails_admin gem own assets.

**Reproduction steps**
Using FontAweaome 5 OR 6 syntax doesn't change anything

**It shows a blank white square**
```ruby
register_instance_option :link_icon do
  'far fa-money-bill-alt'
  # or fa-regular fa-money-bill-1
end
```

**It works because it's solid**
```ruby
register_instance_option :link_icon do
  'fas fa-money-bill-alt'
  # or fa-solid fa-money-bill-1
end
```

**Additional context**

- `rails` version: 6.1.6
- `rails_admin` version: 3.1.1
- `rails_admin` npm package version: none, using sprockets

**Comment by newfylox** [comment]
I don't know if it's relied to this but using my app (and not `rails_admin`), it always tries to load `fa-solid` font, even if nowhere I ask it. It falls in my compiled assets.

![2023-01-26_11-18](https://user-images.githubusercontent.com/3361669/214889643-5ac144cd-55ae-4a43-b2c6-b383fb4648ee.png)

**Comment by mshibuya** [comment]
That's intentional, we're loading [only solid icons](https://github.com/railsadminteam/rails_admin/blob/e59a9353e742b0f6e6b152d1b1f9e7cafad3ee54/src/rails_admin/styles/base.scss#L15).
To use other icons you need to somehow load other icon fonts, by using [customization](https://github.com/railsadminteam/rails_admin/wiki/Theming-and-customization#customization).
